In [15]:
#import the library
import numpy as np

list = [1, 2, 2, 5, 6, 7, 8]
a=np.array(list)
type(a)

numpy.ndarray

In [4]:
a.shape

(3,)

In [6]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]
l3 = [9, 0, 1, 2]

arr = np.array([l1, l2, l3])

In [7]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [8]:
arr.shape

(3, 4)

In [10]:
#Indexing
a[2]

np.int64(2)

In [11]:
#Change the element
a[2] = 3

In [12]:
a

array([1, 2, 3])

In [13]:
a[1:]

array([2, 3])

In [16]:
a

array([1, 2, 2, 5, 6, 7, 8])

In [17]:
a[1:]

array([2, 2, 5, 6, 7, 8])

In [18]:
a[2] = 3


In [19]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [20]:
a[-1]

np.int64(8)

In [21]:
a[:-1]

array([1, 2, 3, 5, 6, 7])

In [ ]:
a[::-1] #reverse the list

array([8, 7, 6, 5, 3, 2, 1])

In [ ]:
a[::2] #jump element

array([1, 3, 6, 8])

In [24]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [45]:
arr[:,0::3]

array([[1, 4],
       [5, 8],
       [9, 2]])

In [ ]:
arr[:,3] #multi D array indexing

array([4, 8, 2])

In [30]:
arr[1:,1:3]

array([[6, 7],
       [0, 1]])

In [32]:
arr[1:,2:]

array([[7, 8],
       [1, 2]])

In [36]:
arr[:,2:]

array([[3, 4],
       [7, 8],
       [1, 2]])