In [37]:
#import the library
import numpy as np

list = [1, 2, 2, 5, 6, 7, 8]
a=np.array(list)
type(a)

numpy.ndarray

In [82]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [39]:
l1 = [1, 2, 3, 4, 2]
l2 = [5, 6, 7, 8, 3]
l3 = [9, 0, 1, 2, 1]

arr = np.array([l1, l2, l3])

In [40]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [41]:
arr.shape

(3, 5)

In [42]:
#Indexing
a[2]

np.int64(2)

In [43]:
#Change the element
a[2] = 3

In [44]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [45]:
a[1:]

array([2, 3, 5, 6, 7, 8])

In [46]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [47]:
a[1:]

array([2, 3, 5, 6, 7, 8])

In [48]:
a[2] = 3


In [49]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [50]:
a[-1]

np.int64(8)

In [51]:
a[:-1]

array([1, 2, 3, 5, 6, 7])

In [52]:
a[::-1] #reverse the list

array([8, 7, 6, 5, 3, 2, 1])

In [53]:
a[::2] #jump element

array([1, 3, 6, 8])

In [54]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [55]:
arr[:,0::3]

array([[1, 4],
       [5, 8],
       [9, 2]])

In [56]:
arr[:,3] #multi D array indexing

array([4, 8, 2])

In [57]:
arr[1:,1:3]

array([[6, 7],
       [0, 1]])

In [58]:
arr[1:,2:]

array([[7, 8, 3],
       [1, 2, 1]])

In [59]:
arr[:,2:]

array([[3, 4, 2],
       [7, 8, 3],
       [1, 2, 1]])

In [60]:
#EDA
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [61]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [62]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [63]:
a<2

array([ True, False, False, False, False, False, False])

In [64]:
a[a<2]

array([1])

In [65]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [66]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [67]:
arr.reshape(5, 3)

array([[1, 2, 3],
       [4, 2, 5],
       [6, 7, 8],
       [3, 9, 0],
       [1, 2, 1]])

In [68]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [69]:
arr.reshape(5, 3)

array([[1, 2, 3],
       [4, 2, 5],
       [6, 7, 8],
       [3, 9, 0],
       [1, 2, 1]])

In [70]:
#mechanism to create an array
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [71]:
np.arange(1, 20, 2).reshape(5, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [72]:
np.arange(1, 20, 2).reshape(2, 5, 1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [73]:
arr * arr

array([[ 1,  4,  9, 16,  4],
       [25, 36, 49, 64,  9],
       [81,  0,  1,  4,  1]])

In [74]:
a*a

array([ 1,  4,  9, 25, 36, 49, 64])

In [75]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [77]:
np.zeros_like((3, 5))

array([0, 0])

In [78]:
np.random.randint(1, 100, 10)

array([19, 56, 86, 95, 37, 19, 74, 89, 82, 82], dtype=int32)

In [79]:
np.random.randint(1, 100, 4).reshape(2,2)

array([[39, 13],
       [88, 56]], dtype=int32)

In [80]:
np.random.randint(0, 1, 6).reshape(2, 3)



array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [81]:
np.random.randn(5, 6)

array([[ 0.61589103,  0.03231374,  2.4496121 ,  0.46681177,  0.17146494,
         0.69633524],
       [ 1.06408922, -0.65340756,  0.68793777,  0.30464584,  0.84281743,
         1.38818962],
       [ 0.49325148,  0.59739279, -0.28256182,  1.13537409,  0.0768056 ,
         1.12038237],
       [-0.50959119,  1.46278077,  0.82281865, -0.29241679, -0.9888685 ,
        -1.27161026],
       [ 1.59899936, -1.01508   ,  0.69685372, -0.575032  , -1.72185018,
        -0.9401174 ]])