In [19]:
#import the library
import numpy as np

list = [1, 2, 2, 5, 6, 7, 8]
a=np.array(list)
type(a)

numpy.ndarray

In [20]:
a

array([1, 2, 2, 5, 6, 7, 8])

In [21]:
l1 = [1, 2, 3, 4, 2]
l2 = [5, 6, 7, 8, 3]
l3 = [9, 0, 1, 2, 1]

arr = np.array([l1, l2, l3])

In [22]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [23]:
arr.shape

(3, 5)

In [24]:
#Indexing
a[2]

np.int64(2)

In [25]:
#Change the element
a[2] = 3

In [26]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [27]:
a[1:]

array([2, 3, 5, 6, 7, 8])

In [28]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [29]:
a[1:]

array([2, 3, 5, 6, 7, 8])

In [30]:
a[2] = 3


In [31]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [32]:
a[-1]

np.int64(8)

In [33]:
a[:-1]

array([1, 2, 3, 5, 6, 7])

In [34]:
a[::-1] #reverse the list

array([8, 7, 6, 5, 3, 2, 1])

In [35]:
a[::2] #jump element

array([1, 3, 6, 8])

In [36]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [37]:
arr[:,0::3]

array([[1, 4],
       [5, 8],
       [9, 2]])

In [38]:
arr[:,3] #multi D array indexing

array([4, 8, 2])

In [39]:
arr[1:,1:3]

array([[6, 7],
       [0, 1]])

In [40]:
arr[1:,2:]

array([[7, 8, 3],
       [1, 2, 1]])

In [41]:
arr[:,2:]

array([[3, 4, 2],
       [7, 8, 3],
       [1, 2, 1]])

In [42]:
#EDA
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [43]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [44]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [45]:
a<2

array([ True, False, False, False, False, False, False])

In [46]:
a[a<2]

array([1])

In [47]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [48]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [49]:
arr.reshape(5, 3)

array([[1, 2, 3],
       [4, 2, 5],
       [6, 7, 8],
       [3, 9, 0],
       [1, 2, 1]])

In [50]:
arr

array([[1, 2, 3, 4, 2],
       [5, 6, 7, 8, 3],
       [9, 0, 1, 2, 1]])

In [51]:
arr.reshape(5, 3)

array([[1, 2, 3],
       [4, 2, 5],
       [6, 7, 8],
       [3, 9, 0],
       [1, 2, 1]])

In [ ]:
#mechanism to create an array
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [56]:
np.arange(1, 20, 2).reshape(5, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [60]:
np.arange(1, 20, 2).reshape(2, 5, 1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [61]:
arr * arr

array([[ 1,  4,  9, 16,  4],
       [25, 36, 49, 64,  9],
       [81,  0,  1,  4,  1]])

In [62]:
a*a

array([ 1,  4,  9, 25, 36, 49, 64])

In [64]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
np.zeros_like((3, 5))

array([0, 0])

In [73]:
np.random.randint(1, 100, 10)

array([17, 42, 34, 16, 32, 50,  3, 36, 58, 12], dtype=int32)

In [74]:
np.random.randint(1, 100, 4).reshape(2,2)

array([[17, 23],
       [19, 16]], dtype=int32)

In [76]:
np.random.randint(0, 1, 6).reshape(2, 3)



array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [79]:
np.random.randn(5, 6)

array([[-1.30111985, -0.70603881, -0.34916265, -0.60803291,  0.36730002,
        -1.19744914],
       [-1.43281031, -0.20482346,  0.68622404,  0.03297756,  1.50488581,
         1.38021345],
       [ 1.34441289,  0.39177197, -0.17890237,  0.88080612,  1.68173842,
        -0.86783463],
       [ 1.89125048,  0.50870022,  1.44345436, -1.90256732, -1.08400676,
         0.77758173],
       [ 1.59262957,  0.13660276,  0.45306908, -0.42242147, -0.50490212,
         1.50881888]])